name: reclippy

services:
  reclip:
    container_name: reclippy
    build: .
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"
    environment:
      - PORT=8899
      # - HOST=0.0.0.0
    ports: [ 8899:8899 ]
    volumes:
      - ./cookies:/app/cookies
    command: gunicorn -b 0.0.0.0:8899 -w 1 --threads 4 --timeout 600 --access-logfile - app:app
    restart: unless-stopped
